<a href="https://colab.research.google.com/github/sucheerarighthere/BasicProg_DataViz65/blob/main/%5Bdataprep%5D_property_estimator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

หาค่าทางสถิติ ของราคาทรัพย์ / หาความมั่นใจ / แยกนักประเมินสองคนออกมาก่อน

In [8]:
import pandas as pd

In [2]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [40]:
home = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/คำตอบนักประเมิน.xlsx',sheet_name='บ้าน')
home.head()

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,1,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2500000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,100.0
1,2,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2700000.0,"โครงการนี้ราคาเสนอขาย 2,500,000-3,000,000 บาท/...",NaN,4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน,NaN,NaN,NaN,NaN,NaN
2,1,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2200000.0,"5,000-15,000",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
3,2,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2400000.0,"ราคาเสนอขายประมาณ 2,200,000 - 2,500,000 บาท/หลัง",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
4,1,https://nayoo.co/khonkaen/posts/495,บ้านเดี่ยว,มั่นใจ,5900000.0,5000000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN

In [41]:
#หาค่าทางสถิติ ของราคาทรัพย์
home[['ราคาทรัพย์']].describe()

         ราคาทรัพย์
count  1.900000e+02
mean   4.280537e+06
std    2.787971e+06
min    3.900000e+05
25%    2.862750e+06
50%    3.995000e+06
75%    5.000000e+06
max    2.094900e+07

In [42]:
#frequency
freq = home[['ความมั่นใจในการเมินราคาทรัพย์']]
freq.value_counts()

ความมั่นใจในการเมินราคาทรัพย์
มั่นใจ                           189
ไม่มั่นใจ                          1
dtype: int64

In [48]:
a = home[['ID ผู้ประเมิน','ความมั่นใจในการเมินราคาทรัพย์','ประเมินราคาซื้อ-ขาย']]
a

     ID ผู้ประเมิน ความมั่นใจในการเมินราคาทรัพย์  ประเมินราคาซื้อ-ขาย
0                1                        มั่นใจ            2500000.0
1                2                        มั่นใจ            2700000.0
2                1                        มั่นใจ            2200000.0
3                2                        มั่นใจ            2400000.0
4                1                        มั่นใจ            5000000.0
..             ...                           ...                  ...
185              2                        มั่นใจ            5000000.0
186              2                        มั่นใจ            7400000.0
187              2                        มั่นใจ            2500000.0
188              2                        มั่นใจ            3900000.0
189              2                        มั่นใจ            1400000.0

[190 rows x 3 columns]

In [58]:
u1c = a[a['ID ผู้ประเมิน']==1]
u1c.describe()

       ID ผู้ประเมิน  ประเมินราคาซื้อ-ขาย
count          100.0         1.000000e+02
mean             1.0         3.938500e+06
std              0.0         2.368553e+06
min              1.0         6.000000e+05
25%              1.0         2.775000e+06
50%              1.0         3.600000e+06
75%              1.0         4.500000e+06
max              1.0         1.600000e+07

In [59]:
u1c['ความมั่นใจในการเมินราคาทรัพย์'].value_counts()

มั่นใจ    100
Name: ความมั่นใจในการเมินราคาทรัพย์, dtype: int64

In [55]:
u2c = a[a['ID ผู้ประเมิน']==2]
u2c.describe()

       ID ผู้ประเมิน  ประเมินราคาซื้อ-ขาย
count           90.0         8.900000e+01
mean             2.0         4.153258e+06
std              0.0         2.386901e+06
min              2.0         9.900000e+05
25%              2.0         2.600000e+06
50%              2.0         3.900000e+06
75%              2.0         4.900000e+06
max              2.0         1.700000e+07

In [57]:
u2c['ความมั่นใจในการเมินราคาทรัพย์'].value_counts()

มั่นใจ       89
ไม่มั่นใจ     1
Name: ความมั่นใจในการเมินราคาทรัพย์, dtype: int64